// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageManagement.Data;

#nullable disable

namespace StorageManagement.Data.Migrations
{
    [DbContext(typeof(StorageManagementDbContext))]
    partial class StorageManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StorageManagement.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identificator of Product");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date the product have arrived in the storage");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("About the product");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Online image url for the product");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Manufacturer of the product");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of the Product");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasComment("Sale price of the product");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Product type could be RAM,GPU,CPU or Monitor");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Available amount in the storage");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Company that supplies with the product");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Used to change arrival date if it's wrong");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b8d4c0f-0a3f-4c95-9f22-1e4f7c2b9a11"),
                            CreatedOn = new DateTime(2026, 6, 21, 20, 49, 35, 178, DateTimeKind.Utc).AddTicks(4689),
                            Description = "NVIDIA GeForce RTX 4070 Ti gaming graphics card with 12GB GDDR6X memory.",
                            ImageUrl = "https://dlcdnwebimgs.asus.com/gain/32d8b7ad-5b28-485b-b440-54813c57e4cb/w692",
                            Manufacturer = "ASUS",
                            Name = "ASUS TUF Gaming GeForce RTX 4070 Ti 12GB",
                            Price = 899.99m,
                            ProductType = "Video Card",
                            Quantity = 5,
                            Supplier = "ASUS"
                        },
                        new
                        {
                            Id = new Guid("2f4f1a7d-8d15-4c7e-b5a1-3b31797b1c21"),
                            CreatedOn = new DateTime(2026, 6, 21, 20, 49, 35, 178, DateTimeKind.Utc).AddTicks(4701),
                            Description = "AMD Ryzen 7 7800X3D desktop processor with AMD 3D V-Cache technology.",
                            ImageUrl = "https://www.amd.com/content/dam/amd/en/images/products/processors/ryzen/2505503-ryzen-7-7800x3d.jpg",
                            Manufacturer = "AMD",
                            Name = "AMD Ryzen 7 7800X3D",
                            Price = 389.99m,
                            ProductType = "Processor",
                            Quantity = 8,
                            Supplier = "AMD"
                        },
                        new
                        {
                            Id = new Guid("6c1846e2-55a6-4d63-a7d1-936c7a7a7e31"),
                            CreatedOn = new DateTime(2026, 6, 21, 20, 49, 35, 178, DateTimeKind.Utc).AddTicks(4706),
                            Description = "Kingston FURY Beast DDR5 memory kit for gaming and high-performance systems.",
                            ImageUrl = "https://desktop.bg/system/images/355088/original/32gb_2x_16gb_ddr5_5600mhz_kingston_fury_beast_rgb.jpg",
                            Manufacturer = "Kingston",
                            Name = "Kingston FURY Beast DDR5 32GB",
                            Price = 129.99m,
                            ProductType = "RAM",
                            Quantity = 12,
                            Supplier = "Kingston"
                        },
                        new
                        {
                            Id = new Guid("a9df4c1b-29c7-4e52-bf95-7f8d3f76e141"),
                            CreatedOn = new DateTime(2026, 6, 21, 20, 49, 35, 178, DateTimeKind.Utc).AddTicks(4710),
                            Description = "ASUS ROG STRIX B650-A GAMING WIFI AM5 motherboard with DDR5 and PCIe support.",
                            ImageUrl = "https://dlcdnwebimgs.asus.com/files/media/3151EBBB-8450-43F6-9994-D7E5E6A9D0E5/v1/img/spec/performance-m.png",
                            Manufacturer = "ASUS",
                            Name = "ASUS ROG STRIX B650-A GAMING WIFI",
                            Price = 269.99m,
                            ProductType = "Motherboard",
                            Quantity = 6,
                            Supplier = "ASUS"
                        },
                        new
                        {
                            Id = new Guid("d42a62ff-12ef-4c6f-9b7e-71a6f9e29c88"),
                            CreatedOn = new DateTime(2026, 6, 21, 20, 49, 35, 178, DateTimeKind.Utc).AddTicks(4713),
                            Description = "27-inch WQHD gaming monitor with IPS panel and up to 165Hz refresh rate.",
                            ImageUrl = "https://media.mts.ee/eyJidWNrZXQiOiJtdHMtcHJvZHVjdC1pbWFnZXMiLCJrZXkiOiIwXC8wNFwvMDQ2ZmQyNWNiZTIwZTBmZTM2NDNlOGJhMTFmNGU0OTMuanBnIiwiZWRpdHMiOnsicmVzaXplIjp7IndpZHRoIjoxMjAwLCJoZWlnaHQiOjYzMCwiZml0IjoiY29udGFpbiIsImJhY2tncm91bmQiOnsiciI6MjU1LCJnIjoyNTUsImIiOjI1NSwiYWxwaGEiOjF9fX19",
                            Manufacturer = "ASUS",
                            Name = "ASUS TUF Gaming VG27AQ",
                            Price = 329.99m,
                            ProductType = "Monitor",
                            Quantity = 4,
                            Supplier = "ASUS"
                        },
                        new
                        {
                            Id = new Guid("ef3b4d91-83b7-4b3e-b51f-9d11b8f8c901"),
                            CreatedOn = new DateTime(2026, 6, 21, 20, 49, 35, 178, DateTimeKind.Utc).AddTicks(4718),
                            Description = "Premium dual-tower CPU cooler with two 140mm fans.",
                            ImageUrl = "https://ardes.bg/uploads/original/noctua-ohladitel-cpu-cooler-nh-d15-g2-lbc-565288.jpg",
                            Manufacturer = "Noctua",
                            Name = "Noctua NH-D15",
                            Price = 109.99m,
                            ProductType = "CPU Cooler",
                            Quantity = 7,
                            Supplier = "Noctua"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
